# Generated by Django 5.2 on 2025-04-22 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedfile",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="encryptedfile",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
